export const differentials = {
  'leisure': 'Área de Lazer',
  'adult-pool': 'Piscina Adulto',
  'kids-pool': 'Piscina Infantil',
  'dry-deck': 'Deck Seco',
  'wet-deck': 'Deck Piscina',
  'party-hall': 'Salão de Festas',
  'playground': 'Playground',
  'playroom': 'Brinquedoteca',
  'zen-lounge': 'Espaço Zen',
  'noble-area': 'Região Nobre',
  'rooftop': 'Rooftop',
  'pool': 'Piscina',
  'external-lounge': 'Lounge Externo',
  'fireplace-lounge': 'Lounge com Lareira',
  'gym': 'Academia',
  'kids-room': 'Espaço Kids',
  'sea-view': 'Vista para o mar',
  'beach-area': 'Perto da praia',
  'grill': 'Churrasqueira',
  'gourmet-lounge': 'Área Gourmet',
  'decorated-hall': 'Hall Decorado',
  'garage': 'Garagem',
  'storage': 'Depósito',
  'balcony': 'Varanda',
}
