import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html lang="pt">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://api.fontshare.com/css?f[]=satoshi@300,301,400,401,500,501,700,701,900,901&display=swap"
          rel="stylesheet"
        />
        <meta
          name="facebook-domain-verification"
          content="judrkaywuvzux703ez2d1cpv31tqrm"
        />
      </Head>
      <body>
        <Main />
        <NextScript />
        <script
          type="text/javascript"
          async
          src="https://d335luupugsy2.cloudfront.net/js/loader-scripts/a3a1172b-ccbf-41dd-ac9a-35c63259f972-loader.js"
        />
      </body>
    </Html>
  );
}
