import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="pt">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://api.fontshare.com/css?f[]=satoshi@300,301,400,401,500,501,700,701,900,901&display=swap" rel="stylesheet"/>
        <meta name="facebook-domain-verification" content="judrkaywuvzux703ez2d1cpv31tqrm" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}