import { Container, Typography } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import { HeroSection } from '../src/components/homePage/HeroSection'
import { HistorySection } from '../src/components/homePage/HistorySection'

export default function Home() {
  return (
    <>
      <Head>
        <title>Campos Incorporadora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://api.fontshare.com/css?f[]=satoshi@300,301,400,401,500,501,700,701,900,901&display=swap" rel="stylesheet"/>
      </Head>
      <main style={{ height: 'fit-content' }}>
        <HeroSection />
        <HistorySection />
      </main>
    </>
  )
}
