export const enterprises = [
  {
    logo: '/vectors/piazza-san-pietro.svg',
    thumb: '/images/SAN-PIETRO.png',
    image: '/images/piazza-san-pietro-empreendimentos.jpg',
    banner: '/images/campos-incorporadora-san-pietro.jpg',
    pageTitle: 'Inspirado na praça de São Pedro, na cidade do Vaticano.',
    pageText: 'O Piazza San Pietro foi inspirado na praça São Pedro no Vaticano-Itália, onde o arquiteto Benini desenhou sua melhor obra-prima.\n\nInspirados nessa criação Campos traz para Joinville o empreendimento PIAZZA SAN PIETRO, buscando trazer para você e sua família conforto, segurança e elegância que você merece!\n\nLocalizado no América em Joinville, próximo a tudo que você precisa.\n\nCom excelente padrão de acabamento\nO residencial dispõe de áreas de lazer e integração, além das melhores plantas para quem procura conforto para a família.',
    name: 'Piazza San Pietro',
    slug: 'piazza-san-pietro',
    district: 'América',
    city: 'Joinville',
    fullAddress: 'Rua João Pessoa 912, América - Joinville/SC',
    area: 'Área privativa de 108 e 126m²',
    bedrooms: '3 suítes ou 2 suítes e 1 dormitório',
    buildingsQty: 1,
    floorsQty: 8,
    apartmentsTotal: 17,
    apartmentsPerFloor: 3,
    apartmentsOptions: 'Apartamentos com opções de 3 e 2 suítes',
    status: 'Em obras',
    description: `Sacada com churrasqueira a carvão\nDuas vagas de garagem\nAmbientes integrados nos apartamentos\nInfraestrutura para sistema de segurança\nInfraestrutura para refrigeração em todos os cômodos`,
    photos: [
      '/images/piazza-san-pietro/Apto_Quarto_Tipo02_Cam01-min.jpg',
      '/images/piazza-san-pietro/Apto_Tipo01_Cam01-min.jpg',
      '/images/piazza-san-pietro/Apto_Tipo01_Cam02-min.jpg',
      '/images/piazza-san-pietro/Apto_Tipo01_Cam03-min.jpg',
      '/images/piazza-san-pietro/Apto_Tipo01_Quarto_Cam01-min.jpg',
      '/images/piazza-san-pietro/Apto_Tipo02_Cam01-min.jpg',
      '/images/piazza-san-pietro/Apto_Tipo02_Cam02-min.jpg',
      '/images/piazza-san-pietro/Campos_SanPietro_Social_Jogos_Cam01-min.jpg',
      '/images/piazza-san-pietro/Campos_SanPietro_Social_Piscina_Cam01-min.jpg',
      '/images/piazza-san-pietro/Campos_SanPietro_Social_Piscina_Cam02-min.jpg',
      '/images/piazza-san-pietro/Espaço_zen_Cam01-min.jpg',
      '/images/piazza-san-pietro/Hall_Entrada_Cam01-min.jpg',
      '/images/piazza-san-pietro/Jardim_Fundos_Cam01 (2)-min.jpg',
      '/images/piazza-san-pietro/Piscina_Cam01 (2)-min.jpg',
      '/images/piazza-san-pietro/Piscina_Cam01-min.jpg',
      '/images/piazza-san-pietro/Piscina_Cam02-min.jpg',
      '/images/piazza-san-pietro/Piscina_Cam03 (1)-min.jpg',
      '/images/piazza-san-pietro/Piscina_Cam03-min.jpg',
      '/images/piazza-san-pietro/Quarto_Tipo01_Cam01-min.jpg',
      '/images/piazza-san-pietro/Salão_Festas_Cam01-min.jpg',
    ],
    differentials: [
      'leisure',
      'adult-pool',
      'kids-pool',
      'dry-deck',
      'wet-deck',
      'party-hall',
      'playground',
      'playroom',
      'zen-lounge',
      'noble-area',
    ],
    plans: [
      {
        label: 'Apto Tipo 1',
        image: '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-planta-1.jpg',
      },
      {
        label: 'Apto Tipo 2',
        image: '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-planta-2.jpg',
      },
      {
        label: 'Apto Tipo 3',
        image: '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-planta-3.jpg',
      },
    ],
    detailedStatus: {
      infrastructure: 1,
      masonry: 0.8,
      installations: 1,
      coating: 0.75,
    }
  },
  {
    logo: '/',
    thumb: '/images/piazza-del-mare.png',
    image: '/images/piazza-del-mare-empreendimentos.jpg',
    banner: '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-lounge-1.jpg',
    name: 'Piazza Del Mare',
    slug: 'piazza-del-mare',
    district: 'Itacolumi',
    city: 'Balneário Piçarras',
    fullAddress: 'Rua 2.900 (Nonato Costa), 79, Itacolomi - Balneário Piçarras',
    area: 'Área privativa de 99 a 123 m²',
    bedrooms: '3 suítes ou 1 suíte e 2 demi-suítes',
    buildingsQty: 1,
    floorsQty: 19,
    apartmentsTotal: 48,
    apartmentsPerFloor: 3,
    status: 'Não inciado',
    description: `Viva a experiência do mais alto nível de qualidade de vida.\nO seu sonho de morar próximo ao mar é possível.\nE o PIAZZA DEL MARE foi feito para realizá-lo.`,
    pageTitle: 'INSPIRADO NA PRAÇA DEL MARE, EM RODI GARGANICO:',
    pageText: 'Rodi Garganico é um pequeno vilarejo italiano cercado de paisagens exuberantes da praia e da natureza. E foi inspirado em paisagens de tirar o fôlego, que o Piazza Del Mare foi projetado.\n\nO mar de Balneário Piçarras foi emoldurado em uma vista única, que pode ser apreciada de dentro do seu próprio apartamento.\n\nE até mesmo o Zico, nosso eterno camisa 10, resolveu descer para Santa Catarina e fazer deste belo empreendimento, a sua próxima jogada.',
    apartmentsOptions: 'Apartamentos com opções de 3 e 2 suítes',
    photos: [
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-academia.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-apartamento-interno-1.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-apartamento-interno-2.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-apartamento-interno-3.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-apartamento-interno-4.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-apartamento-interno-5.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-apartamento-interno-6.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-brinquedoteca.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-fachada-1.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-fachada-2.jpeg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-lounge-1.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-lounge-2.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-lounge-3.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-lounge-4.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-salao-de-festas.jpg',
    ],
    differentials: [
      'leisure',
      'adult-pool',
      'kids-pool',
      'dry-deck',
      'wet-deck',
      'party-hall',
      'playground',
      'playroom',
      'zen-lounge',
      'noble-area',
    ],
    plans: [
      {
        label: 'Apto Tipo 1',
        image: '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-planta-1.jpg',
      },
      {
        label: 'Apto Tipo 2',
        image: '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-planta-2.jpg',
      },
      {
        label: 'Apto Tipo 3',
        image: '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-planta-3.jpg',
      },
    ],
    detailedStatus: {
      infrastructure: 0,
      masonry: 0,
      installations: 0,
      coating: 0,
    }
  },
]