export const enterprises = [
  {
    logo: '/vectors/piazza-san-pietro.svg',
    thumb: '/images/piazza-san-pietro/SAN-PIETRO-card-home.png',
    image: '/images/THUMB_SAN_PIETRO_INICIAL_800x800px.png',
    banner: '/images/campos-incorporadora-san-pietro.jpg',
    pageTitle: 'Inspirado na praça de São Pedro, na cidade do Vaticano:',
    pageText: 'A Piazza San Pietro, localizada no Vaticano aos pés da Basílica de São Pedro, é uma das maiores e mais impressionantes praças do mundo.\n\nInspirado nessa obra-prima, a Campos traz para Joinville o empreendimento Piazza San Pietro.\n\nLocalizado no coração do bairro América, ele traz com todo o conforto e requinte que você e sua família merecem. Veja mais detalhes e permita-se ser surpreendido.',
    name: 'Piazza San Pietro',
    slug: 'piazza-san-pietro',
    district: 'América',
    city: 'Joinville',
    fullAddress: 'Rua João Pessoa 912, América - Joinville/SC',
    area: 'Área privativa de 108 e 126m²',
    bedrooms: '2 ou 3 suítes',
    buildingsQty: 1,
    floorsQty: 8,
    apartmentsTotal: 17,
    apartmentsPerFloor: 3,
    apartmentsOptions: 'Apartamentos com opções de 3 e 2 suítes',
    status: 'Em obras',
    description: `Área privativa de 108 e 126m²\n3 suítes ou 2 suítes e 1 dormitório`,
    photos: [
      '/images/piazza-san-pietro/Apto_Quarto_Tipo02_Cam01-min.jpg',
      '/images/piazza-san-pietro/Apto_Tipo01_Cam01-min.jpg',
      '/images/piazza-san-pietro/Apto_Tipo01_Cam02-min.jpg',
      '/images/piazza-san-pietro/Apto_Tipo01_Cam03-min.jpg',
      '/images/piazza-san-pietro/Apto_Tipo01_Quarto_Cam01-min.jpg',
      '/images/piazza-san-pietro/Apto_Tipo02_Cam01-min.jpg',
      '/images/piazza-san-pietro/Apto_Tipo02_Cam02-min.jpg',
      '/images/piazza-san-pietro/Campos_SanPietro_Social_Jogos_Cam01-min.jpg',
      '/images/piazza-san-pietro/Espaço_zen_Cam01-min.jpg',
      '/images/piazza-san-pietro/Hall_Entrada_Cam01-min.jpg',
      '/images/piazza-san-pietro/Jardim_Fundos_Cam01 (2)-min.jpg',
      '/images/piazza-san-pietro/Quarto_Tipo01_Cam01-min.jpg',
      '/images/piazza-san-pietro/Salão_Festas_Cam01-min.jpg',
      '/images/piazza-san-pietro/_CAMPOS_SAN_PIETRO_PISCINA_R02.png',
      '/images/piazza-san-pietro/Campos_SanPietro_Social_Academia_Cam02.jpg',
      '/images/piazza-san-pietro/Campos_SanPietro_Social_Academia_Cam01.jpg',
      '/images/piazza-san-pietro/Campos_SanPietro_Social_Brinquedoteca_Cam01.jpg',      
    ],
    differentials: [
      'leisure',
      'adult-pool',
      'kids-pool',
      'dry-deck',
      'wet-deck',
      'party-hall',
      'playground',
      'playroom',
      'zen-lounge',
      'noble-area',
    ],
    planText: 'Torre única | 8 andares | 17 aptos. | 3 por andar\n7 Aptos. tipo 1 com 126m² privativos | 3 suítes\n10 Aptos. tipo 2 e 3 com 108m² privativos | 2 suítes e 1 dormitório\n1 cobertura plana com 168m²\n1 cobertura plana com 173m²\nSacada com churrasqueira a carvão\nDuas vagas de garagem\nOpção para a terceira vaga de garagem\nAmbientes integrados nos apartamentos\nInfraestrutura para sistema de segurança\nInfraestrutura para refrigeração em todos os cômodos\nPorcelanato na cozinha, sala e áreas molhadas',
    plans: [
      {
        label: 'Apartamento Tipo 1',
        image: '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-planta-1.jpg',
      },
      {
        label: 'Apartamento Tipo 2',
        image: '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-planta-2.jpg',
      },
      {
        label: 'Apartamento Tipo 3',
        image: '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-planta-3.jpg',
      },
    ],
    detailedStatus: {
      infrastructure: 1,
      masonry: 0.8,
      installations: 1,
      coating: 0.75,
    }
  },
  {
    logo: '/images/DEL_MARE.png',
    thumb: '/images/piazza-del-mare/del-mare-card-home.png',
    image: '/images/PREDIO_DEL_MARE_NOTURNO.png',
    banner: '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-lounge-1.jpg',
    name: 'Piazza Del Mare',
    slug: 'piazza-del-mare',
    district: 'Itacolumi',
    city: 'Balneário Piçarras',
    fullAddress: 'Rua 2.900 (Nonato Costa), 79, Itacolomi - Balneário Piçarras',
    area: 'Área privativa de 99 a 123 m²',
    bedrooms: '3 suítes ou 1 suíte e 2 demi-suítes',
    buildingsQty: 1,
    floorsQty: 19,
    apartmentsTotal: 48,
    apartmentsPerFloor: 3,
    status: 'Lançamento',
    description: `Área privativa de 99 a 123 m²\n3 suítes ou 1 suíte e 2 demi-suítes`,
    pageTitle: 'INSPIRADO NA PRAÇA DEL MARE, EM RODI GARGANICO:',
    pageText: 'Rodi Garganico é um pequeno vilarejo italiano cercado de paisagens exuberantes da praia e da natureza. E foi inspirado em paisagens de tirar o fôlego, que o Piazza Del Mare foi projetado.\n\nO mar de Balneário Piçarras foi emoldurado em uma vista única, que pode ser apreciada de dentro do seu próprio apartamento.\n\nE até mesmo o Zico, nosso eterno camisa 10, resolveu descer para Santa Catarina e fazer deste belo empreendimento, a sua próxima jogada.',
    apartmentsOptions: 'Apartamentos com opções de 3 e 2 suítes',
    planText: 'Torre única / 19 andares / 45 apartamentos / 3 por andar\n15 aptos tipo 1 com 123,61m² privativos / 3 suítes\n15 aptos tipo 3 com 100,14 m² / 1 suíte e 2 demi-suítes\n15 aptos tipo 3 com 100,52 m² privativos / 1 suíte e 2 demi-suítes\nEspaço gourmet no apartamento\nSacada com churrasqueira a carvão\nAmbientes integrados nos apartamentos\nOpção de segunda vaga de garagem\nInfraestrutura para sistema de segurança\n2 elevadores\nEntrega prevista para: Julho/2025',
    photos: [
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-academia.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-apartamento-interno-1.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-apartamento-interno-2.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-apartamento-interno-3.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-apartamento-interno-4.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-apartamento-interno-5.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-apartamento-interno-6.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-brinquedoteca.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-fachada-1.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-fachada-2.jpeg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-lounge-1.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-lounge-2.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-lounge-3.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-lounge-4.jpg',
      '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-salao-de-festas.jpg',
    ],
    differentials: [
      'rooftop',
      'pool',
      'wet-deck',
      'external-lounge',
      'fireplace-lounge',
      'party-hall',
      'gym',
      'kids-room',
      'sea-view',
      'beach-area',
    ],
    plans: [
      {
        label: 'Apartamento Tipo 1',
        image: '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-planta-1.jpg',
      },
      {
        label: 'Apartamento Tipo 2',
        image: '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-planta-2.jpg',
      },
      {
        label: 'Apartamento Tipo 3',
        image: '/images/piazza-del-mare/incorporadora-campos-piazza-del-mare-planta-3.jpg',
      },
    ],
    detailedStatus: {
      infrastructure: 0,
      masonry: 0,
      installations: 0,
      coating: 0,
    }
  },
  {
    hideSections: ['planOptions'],
    logo: '/',
    thumb: '/images/piazza-della-liberta/LIBERTA-card-home.png',
    image: '/images/dellaliberta_800x800px.png',
    banner: '/images/piazza-della-liberta/piazza-della-liberta-salao-de-festas.jpg',
    name: 'Piazza Della Libertá',
    slug: 'piazza-della-liberta',
    district: 'Costa e Silva',
    city: 'Joinville',
    fullAddress: 'Rua Carlos Willy Boehm 738, Costa e Silva - Joinville / SC',
    area: 'Área privativa de 94 a 97m²',
    bedrooms: '2 suítes e 1 dormitório',
    buildingsQty: 1,
    floorsQty: 8,
    apartmentsTotal: 23,
    apartmentsPerFloor: 3,
    status: '100% vendido',
    description: `Área privativa de 94 a 97m²\n2 suítes e 1 dormitório`,
    pageTitle: 'INSPIRADO NA PRAÇA DELLA LIBERTÁ, DE FLORENÇA:',
    pageText: 'A Piazza della Libertá foi construída no século 19, no extremo norte do centro histórico de Florença.\n\nEla fez parte das obras para produzir o Viali di Circonvallazione, um projeto que criou grandes praças, das quais se ramificam vias largas que circundam o centro da cidade\n\nSua arquitetura burguesa e cheia de história, inspirou a criação do residencial Piazza della Libertá\n\n',
    apartmentsOptions: 'Apartamentos com opções de 3 e 2 suítes',
    photos: [      
      '/images/piazza-della-liberta/piazza-della-liberta-fachada-1.jpg',
      '/images/piazza-della-liberta/piazza-della-liberta-fachada-2.jpg',
      '/images/piazza-della-liberta/piazza-della-liberta-fachada-3.jpg',
      '/images/piazza-della-liberta/piazza-della-liberta-hall.jpg',
      '/images/piazza-della-liberta/piazza-della-liberta-piscina.jpg',
      '/images/piazza-della-liberta/piazza-della-liberta-piscina-2.jpg',
      '/images/piazza-della-liberta/piazza-della-liberta-piscina-3.jpg',
      '/images/piazza-della-liberta/piazza-della-liberta-salao-de-festas.jpg',
      '/images/piazza-della-liberta/piazza-della-liberta-salao-de-festas-2.jpg',
      '/images/piazza-della-liberta/piazza-della-liberta-salao-de-festas-3.jpg',
      '/images/piazza-della-liberta/piazza-della-liberta-salao-de-festas-4.jpg',
    ],
    differentials: [
      'grill',
      'gourmet-lounge',
      'pool',
      'party-hall',
      'decorated-hall',
    ],
    plans: [
    ],
    detailedStatus: {
      infrastructure: 1,
      masonry: 1,
      installations: 1,
      coating: 1,
    }
  },
  {
    hideSections: ['planOptions'],
    logo: '/',
    thumb: '/images/piazza-san-carlo/piazzasancarlo-card-home.png',
    image: '/images/PREDIO_SAN_CARLO.png',
    banner: '/images/piazza-san-carlo/piazza-san-carlo-salao-de-festas.png',
    name: 'Piazza San Carlo', 
    slug: 'piazza-san-carlo',
    district: 'Costa e Silva',
    city: 'Joinville',
    fullAddress: 'Rua Senador Nilo Coelho 120, Costa e Silva - Joinville/SC',
    area: 'Área privativa de 39 a 143m²',
    bedrooms: '1 suíte com 1, 2 ou 3 dormitórios',
    buildingsQty: 1,
    floorsQty: 5,
    apartmentsTotal: 17,
    apartmentsPerFloor: 3,
    status: '100% vendido',
    description: `Área privativa de 39 a 122m²\n1 suíte com 1, 2 ou 3 dormitórios`,
    pageTitle: 'INSPIRADO NA PRAÇA SAN CARLO, DE TURIM:',
    pageText: 'Projetada por Carlo di Castellamonte em meados do século 17, a Piazza San Carlo é uma das principais e mais bonitas praças de Turim, na Itália.\n\nSan Carlo é rodeada por edifícios soberbos e possui proporções perfeitas, típicas do estilo barroco. É um lugar para passear e viver momentos inesquecíveis.\n\nE também, o local que inspirou o nosso residencial, Piazza San Carlo.',
    apartmentsOptions: 'Apartamentos com opções de 3 e 2 suítes',
    photos: [
      '/images/piazza-san-carlo/piazza-san-carlo-salao-de-festas.png',
      '/images/piazza-san-carlo/san_carlo_academia.png',
      '/images/piazza-san-carlo/piazza-san-carlo-salao-de-festas.png',
      '/images/piazza-san-carlo/san_carlo_academia.png',
    ],
    differentials: [
      'grill',
      'party-hall',
      'garage',
      'storage',
      'balcony',
    ],
    plans: [
    ],
    detailedStatus: {
      infrastructure: 1,
      masonry: 1,
      installations: 1,
      coating: 1,
    }
  },
  {
    hideSections: ['details','planOptions'],
    logo: '/',
    thumb: '/images/piazza-san-marco/SAN-MARCO-card-home.png',
    image: '/images/SanMarco_800x800px.png',
    banner: '/images/SanMarco_800x800px.png',
    name: 'Piazza San Marco',
    slug: 'piazza-san-marco',
    district: 'Costa e Silva',
    city: 'Joinville',
    fullAddress: 'Rua Professor Humberto Rohden 241, Costa e Silva - Joinville/SC',
    area: 'Área privativa de 38 a 117m²',
    bedrooms: '1 suíte com 1 ou 2 dormitórios',
    buildingsQty: 1,
    floorsQty: 5,
    apartmentsTotal: 14,
    apartmentsPerFloor: 3,
    status: '100% vendido',
    description: `Área privativa de 38 a 135m²\n1 suíte com 1 ou 2 dormitórios`,
    pageTitle: 'INSPIRADO NA PRAÇA SAN MARCO, DE VENEZA:',
    pageText: 'A praça de San Marco, construída no século IX, está localizada no coração de Veneza, juntamente com os edifícios mais representativos da cidade.\n\nEla não só é uma das mais bonitas da Itália, como também uma das mais bonitas do mundo. Napoleão a definiu como “o salão mais bonito da Europa”.\n\nA Piazza San Marco, foi a grande inspiração para a construção deste residencial.',
    apartmentsOptions: 'Apartamentos com opções de 3 e 2 suítes',
    photos: [
    ],
    differentials: [
      'grill',
      'party-hall',
      'playground',
      'decorated-hall',
      'garage',
    ],
    plans: [
    ],
    detailedStatus: {
      infrastructure: 1,
      masonry: 1,
      installations: 1,
      coating: 1,
    }
  },
]