export const enterprises = [
  {
    thumb: '/images/piazza-san-carlo.png',
    image: '/images/piazza-san-carlo-empreendimentos.jpg',
    name: 'Piazza San Carlo',
    slug: 'piazza-san-carlo',
    district: 'América',
    city: 'Joinville',
    area: 'Área privativa entre 148 e 171 m²',
    bedrooms: '3 e 4 dormitórios | 3 suítes',
    buildingsQty: 1,
    floorsQty: 8,
    apartmentsTotal: 17,
    apartmentsPerFloor: 3,
    status: 'Entregue',
    description: `Sacada com churrasqueira a carvão\nDuas vagas de garagem\nAmbientes integrados nos apartamentos\nInfraestrutura para sistema de segurança\nInfraestrutura para refrigeração em todos os cômodos`,
  },
  {
    thumb: '/images/piazza-del-mare.png',
    image: '/images/piazza-del-mare-empreendimentos.jpg',
    name: 'Piazza Del Mare',
    slug: 'piazza-del-mare',
    district: 'Itacolumi',
    city: 'Balneário Piçarras',
    area: 'Área privativa entre 148 e 171 m²',
    bedrooms: '3 e 4 dormitórios | 3 suítes',
    buildingsQty: 1,
    floorsQty: 8,
    apartmentsTotal: 17,
    apartmentsPerFloor: 3,
    status: 'Lançamento',
    description: `Viva a experiência do mais alto nível de qualidade de vida.\nO seu sonho de morar próximo ao mar é possível.\nE o PIAZZA DEL MARE foi feito para realizá-lo.`,
  },
  {
    thumb: '/images/SAN-PIETRO.png',
    image: '/images/piazza-san-pietro-empreendimentos.jpg',
    name: 'Piazza San Pietro',
    slug: 'piazza-san-pietro',
    district: 'América',
    city: 'Joinville',
    area: 'Área privativa entre 148 e 171 m²',
    bedrooms: '3 e 4 dormitórios | 3 suítes',
    buildingsQty: 1,
    floorsQty: 8,
    apartmentsTotal: 17,
    apartmentsPerFloor: 3,
    status: 'Em obras',
    description: `Sacada com churrasqueira a carvão\nDuas vagas de garagem\nAmbientes integrados nos apartamentos\nInfraestrutura para sistema de segurança\nInfraestrutura para refrigeração em todos os cômodos`,
  },
]